# 개인 yml 설정

spring:
  #  DB config(mySql)
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/tutorlink
  #    username : root
  #    password : 1234

  #  DB config(H2)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutorlink
    username: root
    password: 1234

  # JPA config
  jpa:
    #    database: mysql
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      javax:
        persistence:
          validation:
            mode: none

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      #location = 프로젝트 절대경로
      location: /Users/yeonjojang/javaProgramming/workspace/tutorLinkTest/src/main/resources/static/images

server:
  port: 8080

